### ISSUE TITLE
make_tool error 

### ISSUE THREAD

**Issue by lrodri29** [datirium/cwl-airflow-parser#1]
Hello. 

Currently trying to run your code. For some reason when I run a test.py script, I obtain an error stating:

> [2018-08-06 13:06:01,468] {configuration.py:206} WARNING - section/key [cwl/tmp_folder] not found in config
> Traceback (most recent call last):
>   File "test.py", line 22, in <module>
>     cwl_workflow("./my/workflows/my.cwl")
>   File "test.py", line 16, in cwl_workflow
>     dag.create()
>   File "/Users/rodrilm2/aplbrain/cwl-airflow-parser/cwl_airflow_parser/cwldag.py", line 192, in create
>     strict=self.default_args['strict'])
>   File "/Users/rodrilm2/aplbrain/cwl-airflow-parser/cwl_airflow_parser/cwlutils.py", line 84, in load_tool
>     makeTool, kwargs if kwargs else {})
> TypeError: make_tool() takes 5 positional arguments but 6 were given

test.py
```python
from cwl_airflow_parser import CWLDAG, CWLJobDispatcher, CWLJobGatherer
from datetime import timedelta

def cwl_workflow(workflow_file):
    dag = CWLDAG(default_args={
        'owner': 'Luis',
        'email': ['lrodri729@gmail.com'],
        'email_on_failure': False,
        'email_on_retry': False,
        'retries': 20,
        'retry_exponential_backoff': True,
        'retry_delay': timedelta(minutes=30),
        'max_retry_delay': timedelta(minutes=60 * 4)
    },
        cwl_workflow=workflow_file)
    dag.create()
    dag.add(CWLJobDispatcher(dag=dag), to='top')
    dag.add(CWLJobGatherer(dag=dag), to='bottom')

    return dag
 
print(cwl_workflow("./my/workflows/my.cwl"))
```

**Comment by lrodri29** [comment]
Just to clarify. I am simply to find a parser, that takes in a cwl file and returns a dag. I imagine this would do just that? correct?

Thank you for your time.

**Comment by portah** [comment]
Sorry for late answer, was on vacation.
This package is tidily coupled with Airflow & cwltool - it parses CWL file into Airflow DAG. It means that you can trigger this DAG immediately. To execute CWL steps cwltool needs tmp directory. I believe it either has to be provided in config file or just generated in /tmp folder. I'll check again.

Thank you for using/trying this package out.

**Comment by portah** [comment]
I see you already fixed that. I did not put the exact version of cwltool. Would you please do PR?

**Comment by lrodri29** [comment]
No problem, thanks for the tool!
